#!/usr/bin/env python3
"""
cargo-geiger replacement — scans the cargo registry cache for unsafe blocks
in all dependencies listed in Cargo.lock.

This is a quick-and-dirty replacement used because cargo-geiger was not
installable in the artifact environment within the time budget. The output
format is intentionally similar to cargo-geiger's CSV output.
"""
import re
import sys
import os
import glob
import tomllib
import csv
from pathlib import Path

def find_cargo_lock(root: Path) -> Path:
    for p in [root / "Cargo.lock", root / "btv-core" / "Cargo.lock"]:
        if p.exists():
            return p
    raise FileNotFoundError("Cargo.lock not found")

def parse_cargo_lock(lockfile: Path) -> list[dict]:
    """Parse Cargo.lock and return list of {name, version, source}."""
    content = lockfile.read_text()
    pkgs = []
    for block in re.finditer(r"\[\[package\]\]\n(.*?)(?=\n\[\[|\Z)", content, re.DOTALL):
        body = block.group(1)
        name = re.search(r"^name = \"(.*?)\"", body, re.MULTILINE)
        version = re.search(r"^version = \"(.*?)\"", body, re.MULTILINE)
        source = re.search(r"^source = \"(.*?)\"", body, re.MULTILINE)
        if name and version:
            pkgs.append({
                "name": name.group(1),
                "version": version.group(1),
                "source": source.group(1) if source else "local",
            })
    return pkgs

def crate_src_path(name: str, version: str) -> Path | None:
    """Find the extracted crate source in the cargo registry cache."""
    candidates = [
        Path.home() / ".cargo" / "registry" / "src",
    ]
    for base in candidates:
        if not base.exists():
            continue
        for index_dir in base.iterdir():
            crate_dir = index_dir / f"{name}-{version}"
            if crate_dir.exists():
                return crate_dir
    return None

def count_unsafe(crate_dir: Path) -> dict:
    """Count unsafe blocks, unsafe fn, unsafe impl in a crate's .rs files."""
    unsafe_blocks = 0
    unsafe_fns = 0
    unsafe_impls = 0
    files_scanned = 0
    for rs in crate_dir.rglob("*.rs"):
        try:
            text = rs.read_text(errors="ignore")
        except Exception:
            continue
        files_scanned += 1
        # Strip comments to reduce false positives
        text_no_comments = re.sub(r"//.*$", "", text, flags=re.MULTILINE)
        text_no_comments = re.sub(r"/\*.*?\*/", "", text_no_comments, flags=re.DOTALL)
        unsafe_blocks += len(re.findall(r"\bunsafe\s*\{", text_no_comments))
        unsafe_fns += len(re.findall(r"\bunsafe\s+fn\b", text_no_comments))
        unsafe_impls += len(re.findall(r"\bunsafe\s+impl\b", text_no_comments))
    return {
        "files": files_scanned,
        "unsafe_blocks": unsafe_blocks,
        "unsafe_fns": unsafe_fns,
        "unsafe_impls": unsafe_impls,
        "total": unsafe_blocks + unsafe_fns + unsafe_impls,
    }

def main():
    repo_root = Path(__file__).resolve().parent.parent
    lockfile = find_cargo_lock(repo_root)
    print(f"# Scanning {lockfile}", file=sys.stderr)
    pkgs = parse_cargo_lock(lockfile)
    print(f"# {len(pkgs)} packages in Cargo.lock", file=sys.stderr)

    rows = []
    for pkg in pkgs:
        if pkg["source"] == "local":
            # btv-core itself
            crate_dir = repo_root / "btv-core"
            if not crate_dir.exists():
                continue
            location = "LOCAL (btv-core)"
        else:
            crate_dir = crate_src_path(pkg["name"], pkg["version"])
            if crate_dir is None:
                rows.append({**pkg, "files": 0, "unsafe_blocks": 0,
                            "unsafe_fns": 0, "unsafe_impls": 0, "total": 0,
                            "location": "NOT_FOUND"})
                continue
            location = str(crate_dir)
        counts = count_unsafe(crate_dir)
        rows.append({**pkg, **counts, "location": location})

    # CSV output
    out_path = repo_root / "reports" / "cargo_geiger_unsafe_inventory.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=[
            "name", "version", "source", "files",
            "unsafe_blocks", "unsafe_fns", "unsafe_impls", "total",
            "location",
        ])
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in w.fieldnames})

    # Markdown summary
    md_path = repo_root / "reports" / "cargo_geiger_unsafe_inventory.md"
    with md_path.open("w") as f:
        f.write("# Cargo Geiger Unsafe Inventory (manual scan)\n\n")
        f.write("Generated by `scripts/cargo_geiger_replacement.py`.\n\n")
        f.write(f"- Packages in `Cargo.lock`: {len(pkgs)}\n")
        found = sum(1 for r in rows if r["total"] > 0)
        f.write(f"- Packages with `unsafe`: {found}\n")
        f.write(f"- Total `unsafe` occurrences: {sum(r['total'] for r in rows)}\n\n")
        f.write("## Packages with unsafe (sorted by count)\n\n")
        f.write("| Crate | Version | Files | Blocks | Fns | Impls | Total |\n")
        f.write("|---|---|---:|---:|---:|---:|---:|\n")
        for r in sorted(rows, key=lambda x: -x["total"]):
            if r["total"] == 0:
                continue
            f.write(f"| {r['name']} | {r['version']} | {r['files']} | "
                    f"{r['unsafe_blocks']} | {r['unsafe_fns']} | "
                    f"{r['unsafe_impls']} | {r['total']} |\n")
        f.write("\n## Local crate (btv-core)\n\n")
        local = [r for r in rows if r["source"] == "local"]
        for r in local:
            f.write(f"- `{r['name']}` v{r['version']}: {r['total']} unsafe "
                    f"occurrences in {r['files']} files\n")

    print(f"Wrote {out_path}")
    print(f"Wrote {md_path}")

if __name__ == "__main__":
    main()
