#!/usr/bin/env python3
"""
gen_construction_table.py — commit Table 1's Criterion estimates as a CSV
and regenerate its LaTeX (COMSI-2026-04-0112 Round 2, G5c).

section5_benchmarks.tex's header comment claimed Table 1 ("EVERY numeric
cell traces to a committed CSV") while actually hand-transcribing numbers
from `btv-core/target/criterion` — gitignored, so nobody without this
exact target/ directory could verify the claim. This script closes that
gap the same way scripts/gen_section5_tables.py already closes it for
Tables 2/3: read the raw source, write a committed CSV, generate the
LaTeX from that CSV, never by hand.

Usage:
  1. Regenerate the Criterion baseline (in btv-core/):
       cargo bench --features test-support --bench verdict_construction \
           -- verdict_construction --save-baseline construction_provenance
  2. Run this script from the repo root:
       python3 scripts/gen_construction_table.py
"""

import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CRITERION_DIR = REPO_ROOT / "target" / "criterion"
BASELINE = "construction_provenance"
CSV_OUT = REPO_ROOT / "data" / "construction_latency_criterion.csv"
TEX_OUT = REPO_ROOT / "paper1" / "section5_table1_construction.tex"

SIZES = [("64B", 64), ("512B", 512), ("4KiB", 4096)]


def load_estimate(label: str) -> dict:
    path = CRITERION_DIR / f"verdict_construction_{label}" / BASELINE / "estimates.json"
    if not path.exists():
        print(
            f"missing {path} — run: cd btv-core && cargo bench --features "
            f"test-support --bench verdict_construction -- verdict_construction "
            f"--save-baseline {BASELINE}",
            file=sys.stderr,
        )
        sys.exit(1)
    return json.loads(path.read_text())["mean"]


def main() -> int:
    rows = []
    for label, size in SIZES:
        mean = load_estimate(label)
        rows.append({
            "context_size_label": label,
            "context_size_bytes": size,
            "lower_ns": mean["confidence_interval"]["lower_bound"],
            "mean_ns": mean["point_estimate"],
            "upper_ns": mean["confidence_interval"]["upper_bound"],
            "confidence_level": mean["confidence_interval"]["confidence_level"],
        })

    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print(f"Wrote {CSV_OUT}", file=sys.stderr)

    out = []
    w = out.append
    w("% ── Table: construction latency (generated; do not edit) ──")
    w("\\begin{table}[t]")
    w("\\caption{Latency of \\texttt{Verdict::new} by context size (Criterion")
    w("95\\% CI; \\texttt{rustc}~1.98.1). Includes authority-signed token")
    w("issuance and verification. Provenance:")
    w("\\texttt{data/construction\\_latency\\_criterion.csv}, generated by")
    w("\\texttt{scripts/gen\\_construction\\_table.py} from")
    w("\\texttt{btv-core/target/criterion} (regenerate with")
    w("\\texttt{cargo bench --features test-support --bench")
    w("verdict\\_construction -- verdict\\_construction --save-baseline")
    w("construction\\_provenance}).}")
    w("\\label{tab:construction}")
    w("\\begin{tabular}{lrrr}")
    w("\\hline")
    w("\\textbf{Context size} & \\textbf{Lower} & \\textbf{Mean} & \\textbf{Upper} \\\\")
    w("\\hline")
    for r in rows:
        w(
            f"{r['context_size_label']} & {r['lower_ns'] / 1e3:.3f}~\\textmu s & "
            f"{r['mean_ns'] / 1e3:.3f}~\\textmu s & {r['upper_ns'] / 1e3:.3f}~\\textmu s \\\\"
        )
    w("\\hline")
    w("\\end{tabular}")
    w("\\end{table}")

    TEX_OUT.write_text("\n".join(out) + "\n")
    print(f"Wrote {TEX_OUT}", file=sys.stderr)
    print(
        f"Floor (64B): {rows[0]['mean_ns'] / 1e3:.3f} us; "
        f"4KiB: {rows[-1]['mean_ns'] / 1e3:.3f} us",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
